config/routes.rb
Stack::Application.routes.draw do

  root 'questions#index_15'
  get  '/questions/search_questions/:tag_id' => 'questions#search_questions_by', as: 'search_questions'
  get  '/questions/sort_by_rating' => 'questions#sort_by_rating', as: 'sort_by_rating'

  resources :users
  resources :questions do
    resources :answers do
      resources :votes
    end
    resources :votes
  end
  resources :tags

  get  'answers/best_answer/:answer_id' => 'answers#best_answer', as: 'best_answer'
  get  'answers/not_best_answer/:answer_id' => 'answers#not_best_answer', as: 'not_best_answer'

  get  'votes/perform_vote_for/:what, :id, :how' => 'votes#perform_vote_for', as: 'perform_vote_for'
  get  'votes/unvote/:what, :id' => 'votes#unvote', as: 'unvote'

  get  '/login'   => 'sessions#index', as: 'login'
  post '/login'   => 'sessions#create'
  get  '/logout'  => 'sessions#destroy', as: 'logout'
  post '/questions/new' => 'questions#create'

  

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
  has_many :votes


  def score
    up = votes.where('vote = ?', 'up').count
    down = votes.where('vote = ?', 'down').count
    up - down
  end

end

app/models/question.rb
class Question < ActiveRecord::Base

  validates_presence_of :title, :description, :tags

  has_and_belongs_to_many :tags
  belongs_to :user
  has_many :answers
  has_many :votes

  def tages=(tages)
    tages = tages.split(', ').map do |tag|
      Tag.where(name: tag).first_or_create
    end
    @tages = tages
  end

  def tages
    @tages
  end

  def score
    up = votes.where('vote = ?', 'up').count
    down = votes.where('vote = ?', 'down').count
    up - down
  end


end

app/models/tag.rb
class Tag < ActiveRecord::Base

  has_and_belongs_to_many :questions

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :questions
  has_many :answers
  has_many :votes

  validates_uniqueness_of :email
end

app/models/vote.rb
class Vote < ActiveRecord::Base

  belongs_to :user
  belongs_to :question
  belongs_to :answer

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.build(answer_params)
    @answer.user = current_user
    @answer.save

    redirect_to question_path(@question)
  end

  def best_answer
    @answer   = Answer.find(params[:answer_id])
    @question = @answer.question
    @best_answer  = @question.answers.where('accepted = ?', true).count

    if @question.user == current_user
      if @answer.user != current_user
        if @best_answer == 0
          @answer.accepted = true
          @answer.save
        else
          redirect_to :back
        end
      else
        redirect_to :back
      end
    end
  end

  def not_best_answer
    @answer   = Answer.find(params[:answer_id])
    @question = @answer.question
    if @question.user == current_user
      @answer.accepted = false
      @answer.save
      redirect_to :back
    else
      redirect_to :back
    end
  end

  private
  def  answer_params
    params.require(:answer).permit(:body)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :login, :logout, :authenticate_user, :check_current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def login(user)
    session[:user_id] ||= user[:id]
  end

  def logout
    session[:user_id] = nil
  end

  def authenticate_user
    if current_user.nil?
      redirect_to login_path
    end
  end

  def check_current_user(user)
    user == current_user
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  before_action :authenticate_user, except: [:index,:index_15, :show]

  def index_15
    @question = Question.order('created_at desc').limit(15)
  end

  def sort_by_rating
    @question = Question.order('rating desc')
  end

  def index
    @question = Question.order('created_at desc')
  end

  def show
    @question = Question.find(params[:id])
    @question.views+=1
    @question.save
    @answer = Answer.new
  end

  def new
    @question = Question.new
  end

  def search_questions_by
    @question = Tag.find(params[:tag_id]).questions
  end

  def destroy
    @question = Question.find(params[:id])

      if @question.tags.present?
        @question.tags.each do |tag|
          check_tag(tag.id)
        end
      end

    @question.destroy
    redirect_to root_path
  end

  def create

    @question = Question.new(question_params)
    tags = @question.tages
    @question.tags << tags
    @question.user = @current_user

    if @question.save
      redirect_to question_path(@question)
    else
      render :new
    end
  end


  private
  def  question_params
    params.require(:question).permit(:title, :description, :tages)
  end

  def check_tag(id)
    tag = Tag.find(id)
      if tag.questions.size == 1
        tag.delete
      end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def index

  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] ||= user.id
      redirect_to root_path
    else
      render "index"
    end
  end

  def destroy
    logout
    redirect_to root_path
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tag = Tag.all
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    begin
      @user = User.find(params[:id])
      unless @user
        redirect_to root_path
      end
    rescue
      redirect_to root_path
    end

  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login(@user)
      redirect_to root_path, notice: "User created succ"
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  before_action :authenticate_user

  def perform_vote_for
    smth = params[:what].constantize.find(params[:id])
    how  = params[:how]
    if user_created smth
      redirect_to :back                                       # Here must be notification: "You can't vote for your creation!"
    else
      if how == 'up'
        if smth.votes.where('vote = ? and user_id =?', how, current_user.id).count == 0
          smth.votes.where('vote = ? and user_id =?', 'down', current_user.id).delete_all if smth.votes.where('vote = ? and user_id =?', 'down', current_user.id).count != 0
          smth.votes <<  Vote.new(vote: how, user_id: current_user.id)
          smth.rating = smth.score
          smth.save
          redirect_to :back
        else
          redirect_to :back                                   #Already voted
        end

      elsif how == 'down'
        if smth.votes.where('vote = ? and user_id =?', how, current_user.id).count == 0
          smth.votes.where('vote = ? and user_id =?', 'up', current_user.id).delete_all if smth.votes.where('vote = ? and user_id =?', 'up', current_user.id).count != 0
          smth.votes << Vote.new(vote: how, user_id: current_user.id)
          smth.rating = smth.score
          smth.save
          redirect_to :back
        else
          redirect_to :back                                   #Already voted
        end
      end
    end
  end

  def unvote
    smth = params[:what].constantize.find(params[:id])
    smth.votes.where('user_id =?', current_user.id).delete_all
    smth.save
    redirect_to :back
  end

  private

  def user_created(what)
    what.user == current_user
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/answers/_answer.html.erb
<div class="
    <% if answer.accepted %>
    <%= 'accepted-answer' %>
    <% else %>
    <%= 'answer' %>
    <% end %>
">

  <div class="answer-votes">
    Votes: <%= answer.rating %>
    <% unless answer.user == current_user %>
        <div>
          <%= link_to image_tag('up_yellow.png', size: '20x20'), perform_vote_for_path(answer.class, answer.id, 'up') %>
          <%= link_to image_tag('down_yellow.png', size: '20x20'), perform_vote_for_path(answer.class, answer.id, 'down') %>
        </div>
    <% end %>

  </div>

  <div style="float: left; width: 40px; height: 40px; padding-left: 5px; padding-top: 2px;">
    <% if answer.question.user == current_user %>
    <% if answer.question.answers.where('accepted = ?', true).count == 0 %>
        <%= link_to image_tag('accepted.png', size: '25x25'), best_answer_path(answer.id)%>
    <% end %>
        <%end %>
    <%= link_to image_tag('accepted.png', size: '35x35'), not_best_answer_path(answer.id) if answer.accepted %>
  </div>

  <div class="answer-body">
    <%= answer.body %>
  </div>

  <div class="answer-author">
    Author: <%= answer.user.email %>
  </div>

</div>

app/views/answers/_answer_form.html.erb
<div class="answer-form">
  <div style="margin-top: 10px;">Type your Answer here:</div>
    <%= form_for [@question, @answer] do |f| %>

        <%= f.text_area :body, class: 'answer-field' %>

        <%= f.submit 'Answer!', class: 'answer-button' %>

    <% end %>
</div>

app/views/home/index.html.erb
<div class="header-container">

  <ul>
    <li><%= link_to 'My Stack', root_path%></li>
    <li><%= link_to 'All questions', questions_path %></li>
    <li><%= link_to 'Ask Question', new_question_path %></li>
    <li><%= link_to 'Sign in', login_path unless current_user%></li>
    <li><%= link_to 'Sign up', new_user_path unless current_user%></li>
    <li><%= link_to "Signed in as #{current_user.email}", user_path(current_user.id) if current_user%></li>
    <li><%= link_to 'Logout', logout_path if current_user %></li>
  </ul>

</div>

app/views/questions/_form.html.erb
<div class="question-form">
    <%= form_for :question do |f| %>

        <div class="question-text">
            <%= f.label :title %>
        </div>

        <div class="question-title-field">
            <%= f.text_area :title, class: 'question-title-field' %>
        </div>

        <div class="question-title-field">
            <%= f.text_area :description, class: 'question-description-field' %>
        </div>

        <div class="question-form-tags">
            <%= f.label :tags %>
        </div>

        <div>
            <%= f.text_area :tages, class: 'question-tag-field', placeholder: 'html, css, ruby on rails' %>
        </div>

        <div>
            <%= f.submit 'Ask your question!', class: 'ask-button' %>
        </div>

    <% end %>
</div>

app/views/questions/_question_partial.html.erb
<div class="question cf">

    <div class="circle">
      <div class="circle-text">
        <%= question.views %><br>
        <% if question.views != 1%>
            <%= 'View'.pluralize  %>
        <% else %>
            <%= 'View' %>
        <% end %>
      </div>
    </div>


    <div class="circle">
        <div class="circle-text">
        <%= question.answers.count %><br>
        <% if question.answers.count != 1%>
              <%= 'Answer'.pluralize  %>
        <% else %>
              <%= 'Answer' %>
        <% end %>
        </div>
    </div>

    <div class="circle">
      <div class="circle-text">
        <%= question.score%><br>
        <% if question.score != 1%>
            <%= 'Vote'.pluralize  %>
        <% else %>
            <%= 'Vote' %>
        <% end %>
      </div>
    </div>

    <div class="question-info" >

        <div style="width: 25px;">
          <% if current_user %>
              <% if question.user == current_user %>
                <br>
              <% else %>
                  <% if question.votes.where('user_id = ?', current_user.id).count == 0%>
                      <div style="float: left; ">
                         <%= link_to image_tag('up_yellow.png', size: '25x25'), perform_vote_for_path(question.class, question.id, 'up')%>
                      </div>
                      <br>
                      <div style="float: left; margin-top: 5px; ">
                        <%= link_to image_tag('down_yellow.png', size: '25x25'), perform_vote_for_path(question.class, question.id, 'down')%>
                      </div>
                  <% elsif question.votes.where('user_id = ? and vote = ?', current_user.id, 'up').count == 1%>
                      <div style="float: left; ">
                        <%= link_to image_tag('up_green.png', size: '25x25')%>
                      </div>
                      <br>
                      <div style="float: left; margin-top: 5px; ">
                        <%= link_to image_tag('round_yellow.png', size: '25x25'), unvote_path(question.class, question.id)%>
                      </div>
                  <% elsif question.votes.where('user_id = ? and vote = ?', current_user.id, 'down').count == 1%>
                      <div style="float: left; ">
                        <%= link_to image_tag('round_yellow.png', size: '25x25'), unvote_path(question.class, question.id)%>
                      </div>
                      <br>
                      <div style="float: left; margin-top: 5px; ">
                        <%= link_to image_tag('down_red.png', size: '25x25')%>
                      </div>
                  <% end %>
              <% end %>
          <% else %>
            <div style="float: left; ">
              <%= link_to image_tag('up_yellow.png', size: '25x25'), perform_vote_for_path(question.class, question.id, 'up')%>
            </div>
            <br>
            <div style="float: left; margin-top: 5px; ">
                <%= link_to image_tag('down_yellow.png', size: '25x25'), perform_vote_for_path(question.class, question.id, 'down')%>
            </div>
          <% end %>
        </div>

      <div class="question-title">
        <%= link_to "#{question.title}", question_path(question.id) %>

      </div>

      <div class="question-title-tags">
        <%= render partial: 'questions/tag', locals:  {tags: question.tags} %>
      </div>

    </div>

    <div class="question-management">
        <div>
            Asked: <%= question.created_at.strftime("%d %b %y") %>
        </div>

        <div class="user-info">
            Author: <%= link_to "#{question.user.email}", user_path(question.user)%>
        </div>

        <div class="question-delete">
            <%= button_to 'Delete question', question, class: 'delete-button', method: :delete if check_current_user(question.user)%>
        </div>
    </div>

</div>

app/views/questions/_show_question_partial.html.erb
<%= render partial: 'questions/question_partial', locals: {question: question} %>

<div class="question">
    <div class="question-description">
        <%= @question.description %>
    </div>
</div>

app/views/questions/_tag.html.erb
<% tags.each do |tag| %>
    <span id="tag" >
      <%= link_to "#{tag.name} #{tag.questions.count}", search_questions_path(tag.id) %>
    </span>
<% end %>

app/views/questions/index.html.erb
<div style="font-size: 24px; margin-bottom: 5px">All questions (sort by: <%= link_to 'date', questions_path %> <%= link_to 'rating', sort_by_rating_path %>)</div>


<% @question.each do |question| %>

    <%= render partial: 'questions/question_partial', locals: {question: question} %>

    <br>
<% end %>

app/views/questions/index_15.html.erb
<div style="font-size: 24px; margin-bottom: 5px">Latest questions</div>

<% @question.each do |question| %>

    <%= render partial: 'questions/question_partial', locals: {question: question} %>

    <br>
<% end %>

app/views/questions/new.html.erb
<div style="font-size: 24px; margin-bottom: 5px">Ask Your Question</div>

<div>
  <%= render 'form' %>
</div>

app/views/questions/search_questions_by.html.erb
<% @question.each do |question| %>
    <%= render partial: 'questions/question_partial', locals: {question: question} %>
<% end %>

app/views/questions/show.html.erb
<%= render partial: 'questions/show_question_partial', locals: {question: @question} %>


<div style="margin-top: 10px; font-size: 24px; margin-bottom: 30px;">
    <%= render text: 'Best Answer' if @question.answers.where('accepted = ?', true).count == 1 %>
    <%= render @question.answers.where('accepted = ?', true) %>
</div>

<div style="margin-top: 10px; font-size: 24px;">
  <%= render text: 'Answers:' if @question.answers.count != 0  %>
</div>
<%= render @question.answers.order('rating desc') %>


<div style="margin-top: 30px">
    <% if current_user.nil? %>
      <%= render partial: 'layouts/login_register' %>
      <%else %>
    <%= render partial: 'answers/answer_form' %>
<% end %>

</div>

app/views/questions/sort_by_rating.html.erb
<div style="font-size: 24px; margin-bottom: 5px">All questions (sort by: <%= link_to 'date', questions_path %> <%= link_to 'rating', sort_by_rating_path %>)</div>

<% @question.each do |question| %>

    <%= render partial: 'questions/question_partial', locals: {question: question} %>

    <br>
<% end %>

app/views/tags/index.html.erb
<h2>All Tags</h2>

<%= render partial: 'questions/tag', locals: {tags: @tag} %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

<!--    <% if @user.errors.any? %>
        <div class="errors_explanation">
          <div><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</div>

          <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>-->

    <div class="registration-text">
      <%= f.label :email %><br>
    </div>

    <div>
      <%= f.email_field :email, class: 'registration-field' %>
    </div>

    <div class="registration-text">
      <%= f.label :password %><br>
    </div>

    <div>
      <%= f.password_field :password, class: 'registration-field' %>
    </div>

    <div class="registration-text">
      <%= f.label :password_confirmation %><br>
    </div>

    <div>
      <%= f.password_field :password_confirmation, class: 'registration-field' %>
    </div>

    <div class="button">
      <%= f.submit 'Sign Up!', class: 'button' %>
    </div>

<% end %>

app/views/users/new.html.erb
<div class="registration-form">

    <div class="text-registration">New user registration</div>

    <div>
      <%= render 'form' %>
    </div>

</div>

app/views/users/show.html.erb
<div class="user-page-name">
  <%= @user.email %>


</div>

<div>
    <div>
        <%= image_tag "avatar.jpg", class:'image' %>
    </div>

    <div style="font-size: 18px; margin-top: 25px; float: left; margin-left: 20px;">
      ID #<%= @user.id %>
      <br>
      Registered: <%= @user.created_at.strftime("%d %b %Y")  %>
    </div>
</div>

<div class="user-page-info">
  <div>Total user's questions: <%= @user.questions.count %></div>

  <div>Total user's answers: <%= @user.answers.count %></div>

  <% if @user.answers.where('accepted = ?', true).count !=0 %>
    <div>
        Total user's Best answers <%= @user.answers.where('accepted = ?', true).count %>
    </div>
  <% end %>

</div>